// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYSiKVBCkKX0k5HP5kNwm-0o26O8tD2Ic',
    appId: '1:776558942866:web:141b98afd427cd6dfa644b',
    messagingSenderId: '776558942866',
    projectId: 'todo-clean-architecture-9c676',
    authDomain: 'todo-clean-architecture-9c676.firebaseapp.com',
    storageBucket: 'todo-clean-architecture-9c676.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9APmslQU7bxwGb81TlofKAEH3vI-M6hc',
    appId: '1:776558942866:android:55bbdc4859d445ebfa644b',
    messagingSenderId: '776558942866',
    projectId: 'todo-clean-architecture-9c676',
    storageBucket: 'todo-clean-architecture-9c676.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIeuJNTsPcRrmX8D312xQhaEYlVchbyM4',
    appId: '1:776558942866:ios:3d6a8c6b662f6622fa644b',
    messagingSenderId: '776558942866',
    projectId: 'todo-clean-architecture-9c676',
    storageBucket: 'todo-clean-architecture-9c676.appspot.com',
    iosBundleId: 'com.example.todoCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIeuJNTsPcRrmX8D312xQhaEYlVchbyM4',
    appId: '1:776558942866:ios:00aacd1be7054b84fa644b',
    messagingSenderId: '776558942866',
    projectId: 'todo-clean-architecture-9c676',
    storageBucket: 'todo-clean-architecture-9c676.appspot.com',
    iosBundleId: 'com.example.todoCleanArchitecture.RunnerTests',
  );
}
